# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:

    runs-on: Agent-1

    steps:
    - uses: actions/checkout@v4
    - name: setup node js
      uses: actions/setup-node@v4
      with:
        node-version: '23'

    - name: frontend compile (syntax check)
      run: |
        cd client
        find . -name "*.js" -exec node --check {} +

    - name: backend compile (syntax check)
      run: |
         cd api
         find . -name "*.js" -exec node --check {} +

  gitleaks_scan:
       runs-on: Agent-1
       needs: compile
       steps:
         - name: checkout repo
           uses: actions/checkout@v4
         - name: gitleaks setup
           uses: gitleaks/gitleaks-action@v2

         - name: gitleaks scan
           run: |
             gitleaks detect --source ./client --exit-code 1
             gitleaks detect --source ./api --exit-code 1

  trivy_scan:
     runs-on: Agent-1
     needs: gitleaks_scan
     steps:
       - name: trivy scan for vulnerability
         uses: aquasecurity/trivy-action@0.33.1
         with:
           scan-type: fs
           scan-ref: .
           format: table
           exit-code: '1'
           ignore-unfixed: true
           vuln-type: 'os,library'
           severity: 'HIGH,CRITICAL'

  sonar_scan_frontend:
    runs-on: Agent-1
    needs: trivy_scan
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: sonar scan (client)
      uses: SonarSource/sonarqube-scan-action@v2
      with:
        projectBaseDir: client
        args: >
          
           -Dsonar.projectName=client-frontend
           -Dsonar.projectKey=client-frontend
           -Dsonar.sources=.
           -Dsonar.test.exclusions=**/node_modules/**,**/dist/**,**build/**
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

  sonar_scan_backend:
    runs-on: Agent-1
    needs: sonar_scan_frontend
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: sonar scan (api)
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          projectBaseDir: api
          args: >
          
           -Dsonar.projectName=api-backend
           -Dsonar.projectKey=api-backend
           -Dsonar.sources=.
           -Dsonar.test.exclusions=**/node_modules/**,**/dist/**,**build/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

  docker_build_and_push_backend:
    runs-on: ubuntu-latest
    needs: sonar_scan_backend
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          tags: azarx1/backend:latest
          file: ./api/Dockerfile

  docker_build_and_push_frontend:
      runs-on: ubuntu-latest
      needs: sonar_scan_backend
      steps:
        - name: Checkout
          uses: actions/checkout@v5
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
           context: ./client
           push: true
           tags: azarx1/frontend:latest
           file: ./client/Dockerfile

      
           
         
