# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:

    runs-on: Agent-1

    steps:
    - name: Clean workspace
      run: |
        sudo rm -rf .git
        sudo rm -rf *

    - uses: actions/checkout@v4
    - name: setup node js
      uses: actions/setup-node@v4
      with:
        node-version: '23'

    - name: frontend compile (syntax check)
      run: |
        cd client
        find . -name "*.js" -exec node --check {} +

    - name: backend compile (syntax check)
      run: |
         cd api
         find . -name "*.js" -exec node --check {} +

  gitleaks_scan:
       runs-on: Agent-1
       needs: compile
       steps:
         - name: checkout repo
           uses: actions/checkout@v4
           with:
             fetch-depth: 0
         - name: gitleaks setup
           uses: gitleaks/gitleaks-action@v2

         - name: gitleaks scan
           run: |
             gitleaks detect --source ./client --exit-code 1
             gitleaks detect --source ./api --exit-code 1

  trivy_scan:
     runs-on: Agent-1
     needs: gitleaks_scan
     steps:
       - name: trivy scan for vulnerability
         uses: aquasecurity/trivy-action@0.33.1
         with:
           scan-type: fs
           scan-ref: .
           format: table
           exit-code: '1'
           ignore-unfixed: true
           vuln-type: 'os,library'
           severity: 'HIGH,CRITICAL'

  sonar_scan_frontend:
    runs-on: Agent-1
    needs: trivy_scan
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: sonar scan (client)
      uses: SonarSource/sonarqube-scan-action@v2
      
      with:
        projectBaseDir: client
        args: >
          
           -Dsonar.projectName=client-frontend
           -Dsonar.projectKey=client-frontend
           -Dsonar.sources=.
           -Dsonar.test.exclusions=**/node_modules/**,**/dist/**,**build/**
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

   
    - name: gatecheck
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@v1.2.0
      with:
       scanMetadataReportFile: client/.scannerwork/report-task.txt
      env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
          

  sonar_scan_backend:
    runs-on: Agent-1
    needs: sonar_scan_frontend
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: sonar scan (api)
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          projectBaseDir: api
          args: >
          
           -Dsonar.projectName=api-backend
           -Dsonar.projectKey=api-backend
           -Dsonar.sources=.
           -Dsonar.test.exclusions=**/node_modules/**,**/dist/**,**build/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        

    
      - name: gatecheck
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@v1.2.0
        with:
         scanMetadataReportFile: api/.scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        




  backend_image_build_scan_push:
    runs-on: Agent-1
    needs: sonar_scan_backend
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Login to nexus registry
        uses: docker/login-action@v3
        with:
          registry: http://${{ vars.NEXUS_HOST }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
         context: ./api
         file: ./api/Dockerfile
         tags: ${{ vars.NEXUS_HOST }}/backend:latest
         push: false
         load: true

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: image
          image-ref: ${{ vars.NEXUS_HOST }}/backend:latest
          severity: HIGH,CRITICAL
          vuln-type: os,library
          ignore-unfixed: true
          exit-code: 1

      - name: Push to nexus
        run: docker push ${{ vars.NEXUS_HOST }}/backend:latest



  docker_build_and_push_frontend:
      runs-on: Agent-1
      needs: sonar_scan_backend
      steps:
        - name: Checkout
          uses: actions/checkout@v5
        - name: Login to nexus Docker Registry
          uses: docker/login-action@v3
          with:
            registry: http://${{ vars.NEXUS_HOST }}
            username: ${{ secrets.NEXUS_USERNAME }}
            password: ${{ secrets.NEXUS_PASSWORD }}
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
           context: ./client
           tags: ${{ vars.NEXUS_HOST }}/frontend:latest
           file: ./client/Dockerfile
           push: false
           load: true


        - name: scan frontend image
          uses: aquasecurity/trivy-action@0.33.1
          with:
            scan-type: image
            image-ref:  ${{ vars.NEXUS_HOST }}/frontend:latest
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'
            exit-code: '1'

        - name: push to nexus
          run: docker push ${{ vars.NEXUS_HOST }}/frontend:latest

      
           
         
