# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:

    runs-on: Agent-1

    steps:
    - uses: actions/checkout@v4
    - name: setup node js
      uses: actions/setup-node@v4
      with:
        node-version: '23'

    - name: frontend compile (syntax check)
      run: |
        cd client
        find . -name "*.js" -exec node --check {} +

    - name: backend compile (syntax check)
      run: |
         cd api
         find . -name "*.js" -exec node --check {} +

  gitleaks_scan:
       runs-on: Agent-1
       needs: compile
       steps:
         - name: checkout repo
           uses: actions/checkout@v4
         - name: install gitleaks
           run: |
            curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64.tar.gz \
            | tar -xz
            sudo mv gitleaks /usr/local/bin/gitleaks
            gitleaks version

         - name: Gitleaks scan (client + api)
           run: |
            gitleaks detect --source ./client --redact --exit-code=1
            gitleaks detect --source ./api --redact --exit-code=1
